name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  project-testing:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USER }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest dvc[s3,gdrive] mlflow

      - name: Download NLTK data
        run: |
          python -m pip install --upgrade nltk
          python -c "import nltk; nltk.download('stopwords'); nltk.download('wordnet')"

      - name: Reproduce DVC pipeline
        run: dvc repro

      - name: Run pytest
        run: pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Promote best model to Production
        run: python src/model/promote_model.py
